# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [3]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [4]:
z = np.random.random((10, 10))
z_min, z_max = z.min(), z.max()
print(f"Минимум: {z_min}, Максимум: {z_max}")

Минимум: 0.0050747491884957086, Максимум: 0.9999673383155611


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [7]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z[::-1, ::-1])

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
z = np.random.rand(5, 10)
z -= z.mean(axis=1, keepdims=True)
print(z)

[[-0.36196953  0.07664904  0.3709067  -0.23449953  0.48508764  0.10610844
   0.4184137  -0.32894376 -0.30994238 -0.2218103 ]
 [-0.2154776  -0.30362383  0.51832004 -0.01527305 -0.13324328 -0.10634468
   0.4859343  -0.10828846 -0.13208006  0.01007661]
 [ 0.09249369 -0.45408441  0.06945668 -0.1392217  -0.38319306  0.38166829
   0.12663547  0.12416353  0.34575829 -0.16367678]
 [ 0.44266362 -0.36362681 -0.04024651 -0.38560117 -0.290581    0.52552737
   0.48311127 -0.37106442 -0.20656027  0.20637791]
 [ 0.22644459 -0.03023834  0.33907237 -0.29107318  0.23372061  0.16001433
   0.02026495 -0.02187989 -0.34927091 -0.28705452]]


5. Поменяйте 1 и 2 строки матрицы

In [ ]:
z = np.arange(25).reshape(5, 5)
z[[0, 1]] = z[[1, 0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coordinates = np.column_stack((r, theta))
print(polar_coordinates)

[[0.857668   0.67332426]
 [0.87580537 0.73047143]
 [1.25352143 0.75952696]
 [1.12713296 0.59807518]
 [0.98068538 0.3473184 ]
 [1.29083289 0.85219472]
 [1.19350022 0.59819479]
 [0.41658276 1.31045064]
 [0.71265633 0.26854985]
 [1.03801307 0.66135764]]


7. Заменить максимальный элемент массива на ноль

In [ ]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.11014313 0.28660031 0.24674825 0.39536244 0.08008805 0.
 0.11351953 0.35450114 0.38281805 0.33456986]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
z += np.bincount(i, minlength=len(z))
print(z)

[3. 3. 2. 4. 3. 3. 5. 2. 2. 3.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1, 2, 3, 4, 5])
z_new = np.zeros(len(z) * 4 - 3, dtype=int)
z_new[::4] = z
print(z_new)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100)
v = np.random.uniform(0, 100)
closest_value = z[np.abs(z - v).argmin()]
print(f"Заданное значение: {v}, Ближайшее значение: {closest_value}")

Заданное значение: 31.892821554039806, Ближайшее значение: 32


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])                # int64 (по умолчанию для целых чисел)
np.array([1., 4, 2, 5, 3])              # float64 (по умолчанию для вещественных чисел)
np.array([1, 4, 2, 5, 3], dtype='float128') # float128 (если поддерживается вашей системой)
np.array([1., 4, 2, 5, 3], dtype='complex128') # complex128 (комплексные числа)
np.array([1, 4, 2, 5, 3], dtype='float64')   # float64 (явно указан тип)
np.array([1, 4, 2, 5, 3], dtype='int64')     # int64 (явно указан тип)
np.array([1, 4, 2, 5, 3], dtype='bool')      # bool (1 -> True, все остальные значения -> True)
np.array([1, 4, 2, 5, 3], dtype='str')       # str (строковый тип)
np.array([1, 4, 2, 5, '3'])                  # str (из-за строкового элемента '3')
np.array([1, -4, 2, 0, 1j])                  # complex128 (из-за элемента `1j`)
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'   
# '4' + '1' = '41'

np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
# False (0 -> False) or True (-4 -> True) = True

np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
# False (0 -> False) and True (-4 -> True) = False

np.array([1, -4, 2, 0, True], dtype='int64')[-1]
# Последний элемент = 1 (True -> 1)

np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
# Ошибка: невозможно преобразовать комплексное число в int64.

np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
# Последний элемент = '1j'

np.array([1, 4, 2, 5, '3'])[-1] * 3
# '3' * 3 = '333'
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)        # Матрица 3x5 из единиц, dtype=float
np.full((3, 5), 3.14)               # Матрица 3x5, заполненная числом 3.14
np.linspace(0, 1, 5)                # 5 чисел равномерно от 0 до 1: [0., 0.25, 0.5, 0.75, 1.]
np.diag((1, 3, 5))                  # Диагональная матрица с элементами 1, 3, 5 на диагонали
np.smile((1, 3, 5))                 # Ошибка: функция `smile` не существует
np.random.random((3, 3))            # Случайная матрица 3x3
np.eye(3)                           # Единичная матрица 3x3
np.empty(3)                         # Массив из 3 элементов (неинициализированный, содержит случайные значения)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0, 0]                # 3 (первый элемент)
X[-1, -1]              # 7 (последний элемент)
X[0:1, -1]             # [4] (срез строки 0 и последний столбец)
X[0:2, -1]             # [4, 8]
X[0:2, 0:2]            # [[3, 5], [7, 6]]
X[1, 1:3]              # [6, 8]
X[1, :]                # [7, 6, 8, 8]
X[:, :]                # [[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]]
X[:]                   # То же, что и `X[:, :]`
X[::2, ::2]            # [[3, 2], [1, 7]]
X[0:3:2, 0:3:2]        # [[3, 2], [1, 7]]
X[::-1, ::-1]          # Полностью перевернутая матрица: [[7, 7, 6, 1], [8, 8, 6, 7], [4, 2, 5, 3]]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])                 # Разделит на две части по строкам: [[0-7], [8-15]]
np.split(grid, [2], axis=1)         # Разделит на две части по столбцам: [[0, 1], [2, 3], ...]
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]               # Списки: [1, 2, 3, 3, 2, 1]
np.array([1, 2, 3]) + np.array([3, 2, 1])  # Массивы: [4, 4, 4] (поэлементное сложение)
```

**7**. Как в CodeLab измерить время выполнения кода?
``` python
# Способ 1: Встроенный magic-команда в Jupyter
%timeit np.arange(1000)

# Способ 2: Использование библиотеки time
import time
start = time.time()
np.arange(1000)
end = time.time()
print("Время выполнения:", end - start)
```

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(X)               # Сумма всех элементов
np.sum(X, axis=1)       # Сумма по строкам: [14, 29, 21]
np.sum(X, axis=0)       # Сумма по столбцам: [11, 17, 17, 19]
np.sum(X, axis=2)       # Ошибка: двумерный массив
np.sum(X, 1)            # То же, что и `axis=1`
sum(X)                  # Сумма строк: [[3, 5, ...], ...]
sum(X, 1)               # Ошибка: в `sum` нет параметра `axis`
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3                      # [False, False, False, True]
X < 3                      # [True, True, False, False]
X[X < 3]                   # [1, 2]
X[X > 3]                   # [4]
X[X != 3]                  # [1, 2, 4]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

Скорость: Массивы NumPy используют оптимизированные C/Fortran-библиотеки, что делает их быстрее списков Python.
Меньше памяти: NumPy массивы хранят данные компактно (один тип данных для всех элементов).
Векторизация: Поддержка операций над массивами без циклов, что упрощает код и ускоряет вычисления.